@extends('layouts.admin')
@section('title','Funil comercial | Papirar')
@push('styles')<style>.funnel-step{position:relative;min-height:132px;border-radius:16px;color:#fff;padding:20px;background:linear-gradient(135deg,#0f2344,#173b72)}.funnel-step .number{font-size:2.2rem;font-weight:900}.funnel-step .rate{color:#f4c542;font-weight:800}.metric-card{height:100%;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.metric-card strong{display:block;color:#0f2344;font-size:1.7rem}.filter-card{border-top:3px solid #173b72}.table td,.table th{vertical-align:middle}</style>@endpush
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 font-weight-bold mb-1">Funil comercial e ativação</h1><div class="text-muted">Dados comerciais do banco do Papirar. Visitantes anônimos devem ser consultados no GA4.</div></div></div>
<form class="card filter-card mb-4" method="GET"><div class="card-body row"><div class="col-md-2"><label>De</label><input class="form-control" type="date" name="from" value="{{ $from->toDateString() }}"></div><div class="col-md-2"><label>Até</label><input class="form-control" type="date" name="to" value="{{ $to->toDateString() }}"></div><div class="col-md-3"><label>Curso</label><select class="form-control" name="course_id"><option value="">Todos</option>@foreach($courses as $course)<option value="{{ $course->id }}" @selected($courseId===$course->id)>{{ $course->title }}</option>@endforeach</select></div><div class="col-md-2"><label>Origem</label><input class="form-control" name="source" value="{{ request('source') }}" placeholder="Ex.: google"></div><div class="col-md-2"><label>Campanha</label><input class="form-control" name="campaign" value="{{ request('campaign') }}" placeholder="UTM campaign"></div><div class="col-md-1 d-flex align-items-end"><button class="btn btn-primary btn-block">OK</button></div></div></form>
<div class="row mb-4">@foreach([['Cadastros',$funnel['registrations'],null],['Trials',$funnel['trials'],$rate($funnel['trials'],$funnel['registrations'])],['Ativados',$funnel['activated'],$rate($funnel['activated'],$funnel['registrations'])],['Pagantes',$funnel['paid'],$rate($funnel['paid'],$funnel['trials'])]] as $step)<div class="col-md-3 mb-3"><div class="funnel-step"><div>{{ $step[0] }}</div><div class="number">{{ $step[1] }}</div><div class="rate">{{ $step[2]===null?'Sem base':number_format($step[2],1,',','.').'% de conversão' }}</div></div></div>@endforeach</div>
<div class="row mb-4">@foreach([['Receita','R$ '.number_format($summary['revenue'],2,',','.')],['Pagamentos',$summary['transactions']],['Renovações',$summary['renewals']],['Pendentes',$summary['pending']],['Falhos/cancelados',$summary['failed']]] as $item)<div class="col-md mb-3"><div class="metric-card"><span class="text-muted">{{ $item[0] }}</span><strong>{{ $item[1] }}</strong></div></div>@endforeach</div>
<div class="card mb-4"><div class="card-header"><h3 class="card-title">Resultado por curso</h3></div><div class="table-responsive"><table class="table table-striped mb-0"><thead><tr><th>Curso</th><th>Trials</th><th>Compradores</th><th>Conversão</th><th>Receita</th></tr></thead><tbody>@forelse($byCourse as $row)<tr><td class="font-weight-bold">{{ $row['course']->title }}</td><td>{{ $row['trials'] }}</td><td>{{ $row['buyers'] }}</td><td>{{ $row['rate']===null?'-':number_format($row['rate'],1,',','.').'%' }}</td><td>R$ {{ number_format($row['revenue'],2,',','.') }}</td></tr>@empty<tr><td colspan="5">Sem dados.</td></tr>@endforelse</tbody></table></div></div>
<div class="row"><div class="col-md-6"><div class="card"><div class="card-header"><h3 class="card-title">Origem dos cadastros</h3></div><div class="card-body p-0"><table class="table mb-0">@foreach($sources as $row)<tr><td>{{ $row->source }}</td><td class="text-right font-weight-bold">{{ $row->total }}</td></tr>@endforeach</table></div></div></div><div class="col-md-6"><div class="card"><div class="card-header"><h3 class="card-title">Campanhas</h3></div><div class="card-body p-0"><table class="table mb-0">@foreach($campaigns as $row)<tr><td>{{ $row->campaign }}</td><td class="text-right font-weight-bold">{{ $row->total }}</td></tr>@endforeach</table></div></div></div></div>
<div class="alert alert-info"><strong>Ativação:</strong> aluno cadastrado no período que respondeu ao menos 10 questões e concluiu uma sessão ou realizou uma revisão até a data final.</div>
@endsection
